export const INSERTAR_USUARIO = 'INSERTAR_USUARIO';
export const BORRAR_USUARIO = 'BORRAR_USUARIO';
export const USUARIO_ERROR = 'INSERTAR_USUARIO_ERROR';
export const SELECCIONAR_USUARIO = 'SELECCIONAR_USUARIO';
export const EDITAR_USUARIO = 'EDITAR_USUARIO';
export const OBTENER_USUARIO_EDITAR = 'OBTENER_USUARIO_EDITAR';