export const GET_COMERCIO_ADHERIDO = 'GET_COMERCIO_ADHERIDO';
export const GET_LOCALIDAD = 'GET_LOCALIDAD';
export const GET_CLIENTE = 'GET_CLIENTE';
export const GET_CATEGORIA = 'GET_CATEGORIA';
export const LOADING_DATA_COMERCIO = 'LOADING_DATA_COMERCIO';
export const INSERTAR_COMERCIO = 'INSERTAR_COMERCIO';